<?php

namespace Database\Seeders\Testing\C2MS;

use Illuminate\Database\Seeder;

class EavDatasetsTableSeeder extends Seeder
{
    public function run(): void
    {
        \DB::table('eav_datasets')->truncate();

        \DB::table('eav_datasets')->insert(
            $this->provideData()
        );
    }

    protected function provideData(): array
    {
        return [
            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '03_terror_additional_insured_mi',
                'entity_title' => '03_terror_additional_insured_mi',
                'id' => 5,
                'identifier' => '6ff00ae7-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 853,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '08_terror_surplus_lines_details',
                'entity_title' => '08_terror_surplus_lines_details',
                'id' => 6,
                'identifier' => '6ff17441-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '02_terror_insured_info',
                'entity_title' => '02_terror_insured_info',
                'id' => 7,
                'identifier' => '6ff203ae-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '06_terror_coverage_info_location_mi',
                'entity_title' => '06_terror_coverage_info_location_mi',
                'id' => 8,
                'identifier' => '6ff3eae0-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 101842,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '05_terror_coverage_info',
                'entity_title' => '05_terror_coverage_info',
                'id' => 9,
                'identifier' => '6ff48fcf-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '01_policy_inception_and_expiry',
                'entity_title' => 'Policy Inception and Expiry',
                'id' => 10,
                'identifier' => '6ff55bad-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '04_terror_loss_payees_mi',
                'entity_title' => '04_terror_loss_payees_mi',
                'id' => 11,
                'identifier' => '6ff5a0ca-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 433,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '07_terror_additional_covers',
                'entity_title' => '07_terror_additional_covers',
                'id' => 12,
                'identifier' => '6ff62775-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '08_terror_target_price',
                'entity_title' => '08_terror_target_price',
                'id' => 13,
                'identifier' => '6ff67301-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '10_terror_previous_losses',
                'entity_title' => '10_terror_previous_losses',
                'id' => 14,
                'identifier' => '6ff6ab30-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '11_terror_first_loss_limit',
                'entity_title' => '11_terror_first_loss_limit',
                'id' => 15,
                'identifier' => '6ff6f8b3-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '12_terror_active_assailant',
                'entity_title' => '12_terror_active_assailant',
                'id' => 16,
                'identifier' => '6ff72c4b-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '13_terror_denial_of_access',
                'entity_title' => '13_terror_denial_of_access',
                'id' => 17,
                'identifier' => '6ff766f3-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '14_terror_overlying_policy_details',
                'entity_title' => '14_terror_overlying_policy_details',
                'id' => 18,
                'identifier' => '6ff7a0e0-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '15_terror_confirmation',
                'entity_title' => '15_terror_confirmation',
                'id' => 19,
                'identifier' => '6ff7e232-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:31:19',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => '16_terror_number_locations',
                'entity_title' => '16_terror_number_locations',
                'id' => 20,
                'identifier' => '6ff89a62-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19648,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_04_policy_holder_details',
                'entity_title' => 'DBBv2_04_Policy_Holder_Details',
                'id' => 21,
                'identifier' => '8cf61a4f-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_02_inception_date',
                'entity_title' => 'DBBv2_02_Inception_Date',
                'id' => 22,
                'identifier' => '8cf77e96-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_06_loss_payees_mi',
                'entity_title' => 'DBBv2_06_Loss_Payees_MI',
                'id' => 23,
                'identifier' => '8cf7b7a2-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 25,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_14_confirmation',
                'entity_title' => 'DBBv2_14_Confirmation',
                'id' => 24,
                'identifier' => '8cf82b5b-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_03_target_price',
                'entity_title' => 'DBBv2_03_Target_Price',
                'id' => 25,
                'identifier' => '8cf86315-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_07_surplus_lines',
                'entity_title' => 'DBBv2_07_Surplus_Lines',
                'id' => 26,
                'identifier' => '8cf89995-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_09_cover_information',
                'entity_title' => 'DBBv2_09_Cover_Information',
                'id' => 27,
                'identifier' => '8cf98def-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_01_type_of_cover',
                'entity_title' => 'DBBv2_01_Type_of_Cover',
                'id' => 28,
                'identifier' => '8cf9eb9f-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_11_location_details',
                'entity_title' => 'DBBv2_11_Location_Details',
                'id' => 29,
                'identifier' => '8cfa1d0a-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_10_overlying_policy_details',
                'entity_title' => 'DBBv2_10_Overlying_Policy_Details',
                'id' => 30,
                'identifier' => '8cfa502d-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_05_additional_insured_mi',
                'entity_title' => 'DBBv2_05_Additional_Insured_MI',
                'id' => 31,
                'identifier' => '8cfa8f3a-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 8,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_13_rate_options',
                'entity_title' => 'DBBv2_13_Rate_Options',
                'id' => 32,
                'identifier' => '8cfb08f1-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_08_business_information',
                'entity_title' => 'DBBv2_08_Business_Information',
                'id' => 33,
                'identifier' => '8cfb3a19-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 298,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:07',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_12_location_information_mi',
                'entity_title' => 'DBBv2_12_Location_Information_MI',
                'id' => 34,
                'identifier' => '8cfbfdcd-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 1422,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_05_additional_insured_mi',
                'entity_title' => 'STPv2_05_Additional_Insured_MI',
                'id' => 35,
                'identifier' => 'ca6e73d5-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_13_stock_location_mi',
                'entity_title' => 'STPv2_13_Stock_Location_MI',
                'id' => 36,
                'identifier' => 'ca6e764e-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_09_transit_details',
                'entity_title' => 'STPv2_09_Transit_Details',
                'id' => 37,
                'identifier' => 'ca6e76d6-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_01_type_of_cover',
                'entity_title' => 'STPv2_01_Type_of_Cover',
                'id' => 38,
                'identifier' => 'ca6e7736-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_02_inception_date',
                'entity_title' => 'STPv2_02_Inception_Date',
                'id' => 39,
                'identifier' => 'ca6e778d-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_11_outgoing_transit_details',
                'entity_title' => 'STPv2_11_Outgoing_Transit_Details',
                'id' => 40,
                'identifier' => 'ca6e77fb-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_12_stock_details',
                'entity_title' => 'STPv2_12_Stock_Details',
                'id' => 41,
                'identifier' => 'ca6e784f-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_07_surplus_lines',
                'entity_title' => 'STPv2_07_Surplus_Lines',
                'id' => 42,
                'identifier' => 'ca6e7dcb-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_03_target_price',
                'entity_title' => 'STPv2_03_Target_Price',
                'id' => 43,
                'identifier' => 'ca6e7ef9-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_14_confirmation',
                'entity_title' => 'STPv2_14_Confirmation',
                'id' => 44,
                'identifier' => 'ca6e7f83-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_06_loss_payees_mi',
                'entity_title' => 'STPv2_06_Loss_Payees_MI',
                'id' => 45,
                'identifier' => 'ca6e800f-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_08_business_information',
                'entity_title' => 'STPv2_08_Business_Information',
                'id' => 46,
                'identifier' => 'ca6e8084-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_10_incoming_transit_details',
                'entity_title' => 'STPv2_10_Incoming_Transit_Details',
                'id' => 47,
                'identifier' => 'ca6e80f9-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_04_policy_holder_details',
                'entity_title' => 'STPv2_04_Policy_Holder_Details',
                'id' => 48,
                'identifier' => 'ca6e8175-c5af-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-07-29 14:58:37',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'ter_03_01_additional_insured_no',
                'entity_title' => 'TER_03_01_Additional_Insured_no',
                'id' => 49,
                'identifier' => 'd00ba88c-d17f-11ea-9667-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19614,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-07-29 14:59:15',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'ter_03_02_loss_payees_no',
                'entity_title' => 'TER_03_02_Loss_Payees_No',
                'id' => 50,
                'identifier' => '1cd40799-d180-11ea-9667-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 19614,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-11-12 15:03:10',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'ter_16_underwriting_dataset',
                'entity_title' => 'TER_16_Underwriting_Dataset',
                'id' => 51,
                'identifier' => '2da4a4e4-24f8-11eb-ae0d-0ace2615376e',
                'location_id' => 1,
                'num_entries' => 7449,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-12-09 13:07:08',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbb_15_underwriting_dataset',
                'entity_title' => 'DBB_15_Underwriting_Dataset',
                'id' => 52,
                'identifier' => '714ec19c-3a1f-11eb-9727-0a8fd383ea9a',
                'location_id' => 1,
                'num_entries' => 2910,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-01-29 15:30:59',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_04_01_additional_insured_no',
                'entity_title' => 'DBBv2_04_01_Additional_Insured_no',
                'id' => 53,
                'identifier' => 'fcfa203c-6246-11eb-ac2b-0a8fd383ea9a',
                'location_id' => 1,
                'num_entries' => 1698,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-01-29 15:31:43',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbbv2_04_02_loss_payee_no',
                'entity_title' => 'DBBv2_04_02_Loss_payee_no',
                'id' => 54,
                'identifier' => '170a4d19-6247-11eb-ac2b-0a8fd383ea9a',
                'location_id' => 1,
                'num_entries' => 1698,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_05_additional_insured_mi',
                'entity_title' => 'STPv2_05_Additional_Insured_MI',
                'id' => 101,
                'identifier' => '91db482e-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 1857,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_01_type_of_cover',
                'entity_title' => 'STPv2_01_Type_of_Cover',
                'id' => 104,
                'identifier' => '91dd95e7-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 5511,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_02_inception_date',
                'entity_title' => 'STPv2_02_Inception_Date',
                'id' => 105,
                'identifier' => '91ddcb34-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 5511,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_07_surplus_lines',
                'entity_title' => 'STPv2_07_Surplus_Lines',
                'id' => 108,
                'identifier' => '91df5fda-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 5511,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_03_target_price',
                'entity_title' => 'STPv2_03_Target_Price',
                'id' => 109,
                'identifier' => '91dfe4c2-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 5511,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_06_loss_payees_mi',
                'entity_title' => 'STPv2_06_Loss_Payees_MI',
                'id' => 111,
                'identifier' => '91e06a84-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 1332,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2020-06-04 17:32:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_04_policy_holder_details',
                'entity_title' => 'STPv2_04_Policy_Holder_Details',
                'id' => 114,
                'identifier' => '91e22b22-a678-11ea-b4d4-4a28775f739c',
                'location_id' => 1,
                'num_entries' => 5510,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-05-11 12:49:26',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_04_02_loss_payee_no',
                'entity_title' => 'STPv2_04_02_Loss_payee_no',
                'id' => 121,
                'identifier' => '517eeb2b-b257-11eb-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5465,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-05-11 12:52:09',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_04_01_additional_insured_no',
                'entity_title' => 'stpv2_04_01_additional_insured_no',
                'id' => 122,
                'identifier' => 'b27d6021-b257-11eb-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5465,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-15 10:19:50',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stp_v2_08_rework_financial_information',
                'entity_title' => 'STP V2 08 Rework Financial Information',
                'id' => 123,
                'identifier' => '75f88adc-160e-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-15 11:41:37',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_09_rework_incoming_stock_details',
                'entity_title' => 'STPv2 09 Rework Incoming Stock Details',
                'id' => 124,
                'identifier' => 'e2d17e03-1619-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-15 11:53:12',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_10_rework_outgoing_stock_details',
                'entity_title' => 'STPv2 10 Rework Outgoing Stock Details',
                'id' => 125,
                'identifier' => '80e67e5c-161b-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-15 12:02:04',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_11_rework_general_transit_details',
                'entity_title' => 'STPv2 11 Rework General Transit Details',
                'id' => 126,
                'identifier' => 'bddcbfe3-161c-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-15 12:07:13',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_rework_12_stock_details',
                'entity_title' => 'STPv2 Rework 12 Stock Details',
                'id' => 127,
                'identifier' => '7609442c-161d-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-15 13:30:16',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_12_2_rework_building_mi_info',
                'entity_title' => 'STPv2 12_2 Rework Building MI Info',
                'id' => 128,
                'identifier' => '106793d2-1629-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 6232,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-20 09:56:17',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_13_claim_details',
                'entity_title' => 'STPv2 13 Claim Details',
                'id' => 129,
                'identifier' => 'ff5d7d1d-19f8-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-20 10:13:01',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_13_rework_declaration',
                'entity_title' => 'STPv2 13 Rework Declaration',
                'id' => 130,
                'identifier' => '55dc3136-19fb-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-20 11:45:39',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_15_rework_tria',
                'entity_title' => 'STPv2 15 Rework TRIA',
                'id' => 131,
                'identifier' => '46ce764f-1a08-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2021-09-20 12:02:47',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_16_underweiting_information',
                'entity_title' => 'STPv2 16 Underweiting Information',
                'id' => 132,
                'identifier' => 'ab68a763-1a0a-11ec-8146-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 5303,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-03-01 14:21:24',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_17_broker_reference',
                'entity_title' => 'STPv2 17 Broker Reference',
                'id' => 133,
                'identifier' => 'dfbc539c-996a-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 3302,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-03-01 14:57:52',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'stpv2_18_overseas_broker',
                'entity_title' => 'STPv2 18 Overseas Broker',
                'id' => 134,
                'identifier' => 'f83bc633-996f-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 3302,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-09 09:04:03',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'dbb_16_wind_season_referrals',
                'entity_title' => 'DBB_16_Wind_Season_Referrals',
                'id' => 151,
                'identifier' => '1c35e964-e7d3-11ec-ac91-0223a3b30884',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-27 10:30:42',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'claims_01_loss_details',
                'entity_title' => 'claims_01_loss_details',
                'id' => 154,
                'identifier' => '322a6345-f604-11ec-bfa1-de8f233d202e',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-27 10:34:14',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'claims_02_contact_details',
                'entity_title' => 'claims_02_contact_details',
                'id' => 155,
                'identifier' => 'b06a0c6a-f604-11ec-bfa1-de8f233d202e',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-27 10:55:21',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'claims_state_01_policyholder_contacted',
                'entity_title' => 'claims_state_01_policyholder_contacted',
                'id' => 156,
                'identifier' => 'a40d5ed4-f607-11ec-bfa1-de8f233d202e',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-27 10:56:56',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'claims_state_02_assessing_coverage',
                'entity_title' => 'claims_state_02_assessing_coverage',
                'id' => 157,
                'identifier' => 'dc5fec75-f607-11ec-bfa1-de8f233d202e',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-28 14:40:13',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'claims_state_03_coverage_outcome',
                'entity_title' => 'claims_state_03_coverage_outcome',
                'id' => 158,
                'identifier' => '38566157-f6f0-11ec-bfa1-de8f233d202e',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-28 14:46:41',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'claims_state_04_adjusting_status',
                'entity_title' => 'claims_state_04_adjusting_status',
                'id' => 159,
                'identifier' => '1f64265d-f6f1-11ec-bfa1-de8f233d202e',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],

            [
                'date_created' => '2022-06-28 14:47:45',
                'date_deleted' => NULL,
                'deleted' => 0,
                'deleted_by' => NULL,
                'entity_code' => 'claims_state_05_indemnity_paid',
                'entity_title' => 'claims_state_05_indemnity_paid',
                'id' => 160,
                'identifier' => '456dc188-f6f1-11ec-bfa1-de8f233d202e',
                'location_id' => 1,
                'num_entries' => 0,
                'revision_id' => 1,
            ],
        ];
    }
}
