<?php

namespace Database\Seeders\Testing\C2MS;

use Illuminate\Database\Seeder;

class EavObjects2datasetsTableSeeder extends Seeder
{
    public function run(): void
    {
        \DB::table('eav_objects2datasets')->truncate();

        \DB::table('eav_objects2datasets')->insert(
            $this->provideData()
        );
    }

    protected function provideData(): array
    {
        return [
            [
                'api_disabled' => NULL,
                'dataset_id' => 5,
                'dataset_revision_id' => 1,
                'id' => 1,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 5,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Additional Insured',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 6,
                'dataset_revision_id' => 1,
                'id' => 2,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 7,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Surplus Lines',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 7,
                'dataset_revision_id' => 1,
                'id' => 3,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 2,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Policy Holder Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 8,
                'dataset_revision_id' => 1,
                'id' => 4,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 12,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Location Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 9,
                'dataset_revision_id' => 1,
                'id' => 5,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 8,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Business Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 10,
                'dataset_revision_id' => 1,
                'id' => 6,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Inception Date',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 11,
                'dataset_revision_id' => 1,
                'id' => 7,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 6,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Loss Payee',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 12,
                'dataset_revision_id' => 1,
                'id' => 8,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 13,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'General Liability',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 13,
                'dataset_revision_id' => 1,
                'id' => 9,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 1,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Target Price',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 14,
                'dataset_revision_id' => 1,
                'id' => 10,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 9,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Financial Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 15,
                'dataset_revision_id' => 1,
                'id' => 11,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 8,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'First Loss Limit',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 16,
                'dataset_revision_id' => 1,
                'id' => 12,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 14,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Active Assailant',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 17,
                'dataset_revision_id' => 1,
                'id' => 13,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 15,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Denial of Access',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 18,
                'dataset_revision_id' => 1,
                'id' => 14,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 10,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Overlying Policy Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 19,
                'dataset_revision_id' => 1,
                'id' => 15,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 16,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Confirmation',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 20,
                'dataset_revision_id' => 1,
                'id' => 16,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 11,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Location Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 21,
                'dataset_revision_id' => 1,
                'id' => 17,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 3,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Policy Holder Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 22,
                'dataset_revision_id' => 1,
                'id' => 18,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 1,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Inception Date',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 23,
                'dataset_revision_id' => 1,
                'id' => 19,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 7,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Loss Payee',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 24,
                'dataset_revision_id' => 1,
                'id' => 20,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 15,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Confirmation',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 25,
                'dataset_revision_id' => 1,
                'id' => 21,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 2,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Target Price',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 26,
                'dataset_revision_id' => 1,
                'id' => 22,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 8,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Surplus Lines',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 27,
                'dataset_revision_id' => 1,
                'id' => 23,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 10,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Cover Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 28,
                'dataset_revision_id' => 1,
                'id' => 24,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Type of Cover',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 29,
                'dataset_revision_id' => 1,
                'id' => 25,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 12,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Location Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 30,
                'dataset_revision_id' => 1,
                'id' => 26,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 11,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Overlying Policy Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 31,
                'dataset_revision_id' => 1,
                'id' => 27,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 5,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Additional Insured ',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 32,
                'dataset_revision_id' => 1,
                'id' => 28,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 14,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Rate Options',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 33,
                'dataset_revision_id' => 1,
                'id' => 29,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 9,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Business Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 34,
                'dataset_revision_id' => 1,
                'id' => 30,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 13,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Location Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 35,
                'dataset_revision_id' => 1,
                'id' => 31,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 4,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Additional Insured',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 36,
                'dataset_revision_id' => 1,
                'id' => 32,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 12,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Stock Location Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 37,
                'dataset_revision_id' => 1,
                'id' => 33,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 8,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Transit Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 38,
                'dataset_revision_id' => 1,
                'id' => 34,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Type of Cover',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 39,
                'dataset_revision_id' => 1,
                'id' => 35,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 1,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Inception Date',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 40,
                'dataset_revision_id' => 1,
                'id' => 36,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 10,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Outgoing Transit Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 41,
                'dataset_revision_id' => 1,
                'id' => 37,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 11,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Stock Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 42,
                'dataset_revision_id' => 1,
                'id' => 38,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 6,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Surplus Lines',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 43,
                'dataset_revision_id' => 1,
                'id' => 39,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 2,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Target Price',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 44,
                'dataset_revision_id' => 1,
                'id' => 40,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 13,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Confirmation',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 45,
                'dataset_revision_id' => 1,
                'id' => 41,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 5,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Loss Payee',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 46,
                'dataset_revision_id' => 1,
                'id' => 42,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 7,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Business Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 47,
                'dataset_revision_id' => 1,
                'id' => 43,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 9,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Incoming Transit Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 48,
                'dataset_revision_id' => 1,
                'id' => 44,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 3,
                'position_index' => 3,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Policy Holder Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 49,
                'dataset_revision_id' => 1,
                'id' => 45,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 3,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'No. of Additional Insured',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 50,
                'dataset_revision_id' => 1,
                'id' => 46,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 4,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'No. of Loss Payees',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 51,
                'dataset_revision_id' => 1,
                'id' => 47,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 1,
                'position_index' => 17,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Underwriting Dataset',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 52,
                'dataset_revision_id' => 1,
                'id' => 48,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 16,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Underwriting Dataset DBB',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 53,
                'dataset_revision_id' => 1,
                'id' => 49,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 4,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'No. of Additional Insured',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 54,
                'dataset_revision_id' => 1,
                'id' => 50,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 6,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'No. of Loss Payees',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 101,
                'dataset_revision_id' => 1,
                'id' => 53,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 5,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 104,
                'dataset_revision_id' => 1,
                'id' => 54,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Type of Cover',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 105,
                'dataset_revision_id' => 1,
                'id' => 55,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 1,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Inception Date',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 108,
                'dataset_revision_id' => 1,
                'id' => 56,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 8,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Surplus Lines',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 109,
                'dataset_revision_id' => 1,
                'id' => 57,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 2,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Target Price',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 111,
                'dataset_revision_id' => 1,
                'id' => 58,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 7,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Loss Payees',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 121,
                'dataset_revision_id' => 1,
                'id' => 59,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 6,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'No. of Loss Payees',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 122,
                'dataset_revision_id' => 1,
                'id' => 60,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 4,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Additional Insured',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 123,
                'dataset_revision_id' => 1,
                'id' => 61,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 9,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Business Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 124,
                'dataset_revision_id' => 1,
                'id' => 62,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 10,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Incoming Transit Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 125,
                'dataset_revision_id' => 1,
                'id' => 63,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 11,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Outgoing Transit Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 126,
                'dataset_revision_id' => 1,
                'id' => 64,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 12,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'General Transit Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 127,
                'dataset_revision_id' => 1,
                'id' => 65,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 13,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Stock Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 128,
                'dataset_revision_id' => 1,
                'id' => 66,
                'is_multiple_instance' => 1,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 14,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Building Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 129,
                'dataset_revision_id' => 1,
                'id' => 67,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 15,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Claim Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 130,
                'dataset_revision_id' => 1,
                'id' => 68,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 18,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Declaration',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 131,
                'dataset_revision_id' => 1,
                'id' => 69,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 19,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Tria',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 132,
                'dataset_revision_id' => 1,
                'id' => 70,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 20,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Underwriting Information',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 114,
                'dataset_revision_id' => 1,
                'id' => 71,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 3,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Policy Holder Details',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 133,
                'dataset_revision_id' => 1,
                'id' => 72,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 16,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Broker Reference',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 134,
                'dataset_revision_id' => 1,
                'id' => 73,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 4,
                'position_index' => 17,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Overseas Broker',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 151,
                'dataset_revision_id' => 1,
                'id' => 74,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 2,
                'position_index' => 17,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Wind Season Referrals',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 154,
                'dataset_revision_id' => 1,
                'id' => 77,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 7,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 155,
                'dataset_revision_id' => 1,
                'id' => 78,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 7,
                'position_index' => 1,
                'revision_id' => 1,
                'step_id' => 2,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 156,
                'dataset_revision_id' => 1,
                'id' => 79,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 8,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 157,
                'dataset_revision_id' => 1,
                'id' => 80,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 9,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 158,
                'dataset_revision_id' => 1,
                'id' => 81,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 10,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 159,
                'dataset_revision_id' => 1,
                'id' => 82,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 11,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],

            [
                'api_disabled' => NULL,
                'dataset_id' => 160,
                'dataset_revision_id' => 1,
                'id' => 83,
                'is_multiple_instance' => 0,
                'location_id' => 1,
                'object_id' => 12,
                'position_index' => 0,
                'revision_id' => 1,
                'step_id' => 1,
                'tab_index' => 0,
                'tab_title' => 'Quote Form',
            ],
        ];
    }
}
