<?php

namespace Database\Seeders\Testing\C2MS;

use Illuminate\Database\Seeder;

class FieldsRevisionsTableSeeder extends Seeder
{
    public function run(): void
    {
        \DB::table('fields_revisions')->truncate();

        \DB::table('fields_revisions')->insert(
            $this->provideData()
        );
    }

    protected function provideData(): array
    {
        return [
            [
                'datasource_id' => 0,
                'datatype_id' => 5,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'text',
                'field_css' => 'inputText form-control',
                'field_id' => 74,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 74,
                'identifier' => '6fec97f6-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 2,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please Specify ...',
                'deleted' => NULL,
                'field_code' => 'country',
                'field_css' => 'inputSelect form-control',
                'field_id' => 75,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 75,
                'identifier' => '6fecbbd8-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 3,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'datepicker',
                'field_css' => 'inputText form-control datepicker',
                'field_id' => 76,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 76,
                'identifier' => '6fece600-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 4,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'textarea',
                'field_css' => 'inputTextarea form-control',
                'field_id' => 77,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 77,
                'identifier' => '6fed0690-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 2,
                'datatype_id' => 5,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'usa_states_main',
                'field_css' => 'inputSelect form-control',
                'field_id' => 78,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 78,
                'identifier' => '6fed89d6-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'yes_no',
                'field_css' => 'form-control',
                'field_id' => 79,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 79,
                'identifier' => '6fedb208-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please Specify ...',
                'deleted' => NULL,
                'field_code' => 'num_additional_named_insured',
                'field_css' => 'inputSelect form-control',
                'field_id' => 80,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 80,
                'identifier' => '6fedd8b0-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 2,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'float_entry',
                'field_css' => 'inputText form-control',
                'field_id' => 81,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 81,
                'identifier' => '6fee0034-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please Select ...',
                'deleted' => NULL,
                'field_code' => 'terror_occupancy_type',
                'field_css' => 'inputSelect form-control',
                'field_id' => 82,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 82,
                'identifier' => '6fee2149-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'terror_coverage_type',
                'field_css' => 'inputSelect form-control',
                'field_id' => 83,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 83,
                'identifier' => '6fee4501-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'Integer',
                'field_css' => 'inputText form-control integer',
                'field_id' => 84,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 84,
                'identifier' => '6fee6793-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'checkbox_agree',
                'field_css' => 'form-control',
                'field_id' => 85,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 85,
                'identifier' => '6fee8450-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'GL_radio',
                'field_css' => 'form-control',
                'field_id' => 86,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 86,
                'identifier' => '6feea596-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbb_losses',
                'field_css' => 'form-control',
                'field_id' => 87,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 87,
                'identifier' => '6feec73b-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please Select ...',
                'deleted' => NULL,
                'field_code' => 'terror_denial_of_access',
                'field_css' => 'inputSelect form-control',
                'field_id' => 88,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 88,
                'identifier' => '6feee8c0-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:31:19',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'No_Locations_Dropdown_10',
                'field_css' => 'inputSelect form-control',
                'field_id' => 89,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 89,
                'identifier' => '6fef1e90-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 5,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'text',
                'field_css' => 'inputText form-control',
                'field_id' => 90,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 90,
                'identifier' => '8cf1d2cc-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 4,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'textarea',
                'field_css' => 'inputTextarea form-control',
                'field_id' => 91,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 91,
                'identifier' => '8cf1f5a3-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 2,
                'datatype_id' => 5,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'usa_states_abbr_all',
                'field_css' => 'inputSelect form-control',
                'field_id' => 92,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 92,
                'identifier' => '8cf21426-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 2,
                'datatype_id' => 5,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'usa_states_main',
                'field_css' => 'inputSelect form-control',
                'field_id' => 93,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 93,
                'identifier' => '8cf2394d-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 2,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please Specify ...',
                'deleted' => NULL,
                'field_code' => 'country',
                'field_css' => 'inputSelect form-control',
                'field_id' => 94,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 94,
                'identifier' => '8cf2b426-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please Specify ...',
                'deleted' => NULL,
                'field_code' => 'num_additional_named_insured',
                'field_css' => 'inputSelect form-control',
                'field_id' => 95,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 95,
                'identifier' => '8cf2ddc7-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 3,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'datepicker',
                'field_css' => 'inputText form-control datepicker',
                'field_id' => 96,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 96,
                'identifier' => '8cf303b8-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'checkbox_agree',
                'field_css' => 'form-control',
                'field_id' => 97,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 97,
                'identifier' => '8cf3224d-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'yes_no',
                'field_css' => 'form-control',
                'field_id' => 98,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 98,
                'identifier' => '8cf34f3e-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 2,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'float_entry',
                'field_css' => 'inputText form-control',
                'field_id' => 99,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 99,
                'identifier' => '8cf371db-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_overlying_wind_deductible',
                'field_css' => 'form-control',
                'field_id' => 100,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 100,
                'identifier' => '8cf391df-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_limit_applicable',
                'field_css' => 'inputSelect form-control',
                'field_id' => 101,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 101,
                'identifier' => '8cf3c365-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_application_overlying_deductible',
                'field_css' => 'form-control',
                'field_id' => 102,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 102,
                'identifier' => '8cf3ed2e-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_type_of_cover',
                'field_css' => 'form-control',
                'field_id' => 103,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 103,
                'identifier' => '8cf411d2-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'No_Locations_Dropdown_100',
                'field_css' => 'inputSelect form-control',
                'field_id' => 104,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 104,
                'identifier' => '8cf43a7a-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_rate_options',
                'field_css' => 'form-control',
                'field_id' => 105,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 105,
                'identifier' => '8cf46096-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_occupancy_type',
                'field_css' => 'inputSelect form-control',
                'field_id' => 106,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 106,
                'identifier' => '8cf48531-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_number_losses',
                'field_css' => 'form-control',
                'field_id' => 107,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 107,
                'identifier' => '8cf4a822-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 4,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_building_age',
                'field_css' => 'form-control',
                'field_id' => 108,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 108,
                'identifier' => '8cf4cb10-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_construction_type',
                'field_css' => 'form-control',
                'field_id' => 109,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 109,
                'identifier' => '8cf4edf9-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_age_roof',
                'field_css' => 'inputSelect form-control',
                'field_id' => 110,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 110,
                'identifier' => '8cf513fe-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:07',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'dbbv2_roof_type',
                'field_css' => 'inputSelect form-control',
                'field_id' => 111,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 111,
                'identifier' => '8cf53721-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 5,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'text',
                'field_css' => 'inputText form-control',
                'field_id' => 112,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 112,
                'identifier' => '91d80f94-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 3,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'datepicker',
                'field_css' => 'inputText form-control datepicker',
                'field_id' => 113,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 113,
                'identifier' => '91d83761-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 4,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'textarea',
                'field_css' => 'inputTextarea form-control',
                'field_id' => 114,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 114,
                'identifier' => '91d85f0d-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 2,
                'datatype_id' => 5,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'usa_states_main',
                'field_css' => 'inputSelect form-control',
                'field_id' => 115,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 115,
                'identifier' => '91d88456-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 2,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please Specify ...',
                'deleted' => NULL,
                'field_code' => 'country',
                'field_css' => 'inputSelect form-control',
                'field_id' => 116,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 116,
                'identifier' => '91d8b034-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'yes_no',
                'field_css' => 'form-control',
                'field_id' => 117,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 117,
                'identifier' => '91d8db13-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 2,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'float_entry',
                'field_css' => 'inputText form-control',
                'field_id' => 118,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 118,
                'identifier' => '91d91069-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stpv2_number_stock_losses',
                'field_css' => 'form-control',
                'field_id' => 119,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 119,
                'identifier' => '91d93643-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stpv2_fire_protection',
                'field_css' => 'form-control',
                'field_id' => 120,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 120,
                'identifier' => '91d96474-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 1,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stpv2_security_details',
                'field_css' => 'form-control',
                'field_id' => 121,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 121,
                'identifier' => '91d9971e-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 1,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please specify ...',
                'deleted' => NULL,
                'field_code' => 'stpv2_iso_codes',
                'field_css' => 'inputSelect form-control',
                'field_id' => 122,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 122,
                'identifier' => '91d9c46f-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'checkbox_agree',
                'field_css' => 'form-control',
                'field_id' => 123,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 123,
                'identifier' => '91d9f226-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 1,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stpv2_number_transit_losses',
                'field_css' => 'form-control',
                'field_id' => 124,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 124,
                'identifier' => '91da1c9e-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stp_coverage_types',
                'field_css' => 'form-control',
                'field_id' => 125,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 125,
                'identifier' => '91da4884-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stpv2_basis_of_valuation',
                'field_css' => 'form-control',
                'field_id' => 126,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 126,
                'identifier' => '91da7583-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'Number_locations_zero_100',
                'field_css' => 'inputSelect form-control',
                'field_id' => 127,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 127,
                'identifier' => '91daa41d-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, select ...',
                'deleted' => NULL,
                'field_code' => 'stp_description_of_operations',
                'field_css' => 'inputSelect form-control',
                'field_id' => 128,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 128,
                'identifier' => '91dad29c-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stpv2_details_perishable_stock',
                'field_css' => 'form-control',
                'field_id' => 129,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 129,
                'identifier' => '91dafa1c-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 1,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-06-04 17:32:16',
                'default_entry_label' => 'Please Specify ...',
                'deleted' => NULL,
                'field_code' => 'num_additional_named_insured',
                'field_css' => 'inputSelect form-control',
                'field_id' => 130,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 130,
                'identifier' => '91db22ba-a678-11ea-b4d4-4a28775f739c',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-09-11 11:09:24',
                'default_entry_label' => 'Please specify the number of losses',
                'deleted' => NULL,
                'field_code' => 'TER_no_losses',
                'field_css' => 'form-control',
                'field_id' => 131,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 131,
                'identifier' => '4060ee38-f41f-11ea-ae0d-0ace2615376e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-10-21 10:11:06',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'DBB_EOC_used',
                'field_css' => 'inputSelect form-control',
                'field_id' => 132,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 132,
                'identifier' => 'bbcd1417-1385-11eb-ae0d-0ace2615376e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2020-12-01 09:19:46',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'Checkbox_Not_Array_Yes',
                'field_css' => 'form-control',
                'field_id' => 133,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 133,
                'identifier' => '5ab1e80c-33b6-11eb-9727-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-04-09 08:11:48',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'fully_sprinklered_checkbok',
                'field_css' => 'form-control',
                'field_id' => 134,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 134,
                'identifier' => '3b94a4f0-990b-11eb-83c8-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-04-09 09:05:07',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'fire_alarm_central_station',
                'field_css' => 'form-control',
                'field_id' => 135,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 135,
                'identifier' => 'adfb74cc-9912-11eb-83c8-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-04-09 09:08:53',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'central_station_burglar_alarm',
                'field_css' => 'form-control',
                'field_id' => 136,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 136,
                'identifier' => '34962576-9913-11eb-83c8-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-04-09 09:09:51',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'security_guards',
                'field_css' => 'form-control',
                'field_id' => 137,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 137,
                'identifier' => '57a37f84-9913-11eb-83c8-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-04-09 09:10:33',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'key_card_access',
                'field_css' => 'form-control',
                'field_id' => 138,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 138,
                'identifier' => '708bb004-9913-11eb-83c8-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-04-09 09:11:23',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'cctv_',
                'field_css' => 'form-control',
                'field_id' => 139,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 139,
                'identifier' => '8e25eefe-9913-11eb-83c8-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-04-09 09:11:57',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'none',
                'field_css' => 'form-control',
                'field_id' => 140,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 140,
                'identifier' => 'a26d85c0-9913-11eb-83c8-0a8fd383ea9a',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-09-15 12:56:14',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'construction_type_stp',
                'field_css' => 'form-control',
                'field_id' => 141,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 141,
                'identifier' => '4f126e0c-1624-11ec-8146-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-09-15 12:58:23',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'building_age_stp',
                'field_css' => 'form-control',
                'field_id' => 142,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 142,
                'identifier' => '9be287a6-1624-11ec-8146-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-09-15 12:58:54',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'roof_age_stp',
                'field_css' => 'form-control',
                'field_id' => 143,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 143,
                'identifier' => 'ae25437d-1624-11ec-8146-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-09-15 13:12:43',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'retrofit_location_stp',
                'field_css' => 'form-control',
                'field_id' => 144,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 144,
                'identifier' => '9c602d78-1626-11ec-8146-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-09-20 10:14:09',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stp_tria_coverage',
                'field_css' => 'form-control',
                'field_id' => 145,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 145,
                'identifier' => '7e8b4fc5-19fb-11ec-8146-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-11-24 07:51:48',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'retrofit_location_stp',
                'field_css' => 'form-control',
                'field_id' => 144,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 146,
                'identifier' => '6077a701-4cfb-11ec-ac91-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 2,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-11-24 07:54:38',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'retrofit_location_stp',
                'field_css' => 'form-control',
                'field_id' => 144,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 147,
                'identifier' => 'c5f30444-4cfb-11ec-ac91-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 3,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-12-21 12:11:27',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'yes_no_unknown',
                'field_css' => 'form-control',
                'field_id' => 146,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 148,
                'identifier' => '1fdd49e0-6257-11ec-ac91-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2021-12-21 12:37:58',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stp_cause_of_loss',
                'field_css' => 'inputSelect form-control',
                'field_id' => 147,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 149,
                'identifier' => 'd3e13a8f-625a-11ec-ac91-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 0,
                'datatype_id' => 9,
                'date_created' => '2022-02-14 08:32:28',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'stp_uuid_mi',
                'field_css' => 'form-control',
                'field_id' => 148,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 150,
                'identifier' => 'a525b6a9-8d70-11ec-ac91-0223a3b30884',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-27 10:13:33',
                'default_entry_label' => 'Please select claim document type',
                'deleted' => NULL,
                'field_code' => 'claims_documents',
                'field_css' => 'inputSelect form-control',
                'field_id' => 149,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 151,
                'identifier' => 'ccbfa08a-f601-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-27 10:14:29',
                'default_entry_label' => 'Please select cause of loss',
                'deleted' => NULL,
                'field_code' => 'claims_cause_of_loss',
                'field_css' => 'inputSelect form-control',
                'field_id' => 150,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 152,
                'identifier' => 'ee94683f-f601-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-27 10:16:48',
                'default_entry_label' => 'Please specify location',
                'deleted' => NULL,
                'field_code' => 'claims_list_of_addresses',
                'field_css' => 'inputSelect form-control',
                'field_id' => 151,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 153,
                'identifier' => '410831d6-f602-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-27 10:18:31',
                'default_entry_label' => 'Please, Select...',
                'deleted' => NULL,
                'field_code' => 'claims_unknown_checkbox',
                'field_css' => 'form-control',
                'field_id' => 152,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 0,
                'id' => 154,
                'identifier' => '7eb98fda-f602-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-27 10:53:39',
                'default_entry_label' => 'Please Specify Method of Contact',
                'deleted' => NULL,
                'field_code' => 'claims_method_of_contact',
                'field_css' => 'inputSelect',
                'field_id' => 153,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 155,
                'identifier' => '66c0d88f-f607-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-27 10:55:53',
                'default_entry_label' => 'Please specify Current Position',
                'deleted' => NULL,
                'field_code' => 'claims_current_position',
                'field_css' => 'inputSelect',
                'field_id' => 154,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 156,
                'identifier' => 'b6b37da7-f607-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-28 13:03:46',
                'default_entry_label' => 'Select coverage outcome',
                'deleted' => NULL,
                'field_code' => 'claims_coverage_outcome',
                'field_css' => 'inputSelect',
                'field_id' => 155,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 157,
                'identifier' => 'beb3bf41-f6e2-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],

            [
                'datasource_id' => 1,
                'datatype_id' => 1,
                'date_created' => '2022-06-28 14:45:57',
                'default_entry_label' => 'Select adjusting status',
                'deleted' => NULL,
                'field_code' => 'claims_adjusting_status',
                'field_css' => 'inputSelect',
                'field_id' => 156,
                'field_inline_css' => NULL,
                'field_placeholder' => '',
                'has_default_entry' => 1,
                'id' => 158,
                'identifier' => '054de4ab-f6f1-11ec-bfa1-de8f233d202e',
                'is_array' => 0,
                'location_id' => 1,
                'ordering_id' => 0,
                'revision_id' => 1,
            ],
        ];
    }
}
